# Generated by Django 4.2.16 on 2024-09-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_response_vacancy_vacancy_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='response',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responses',
            field=models.ManyToManyField(blank=True, to='app.response'),
        ),
    ]
