# Generated by Django 4.2.16 on 2024-09-09 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_vacancy_response_vacancy_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='responses',
        ),
        migrations.AddField(
            model_name='response',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.vacancy'),
        ),
        migrations.AlterField(
            model_name='response',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
